### ISSUE TITLE
Update to 0.15 rollbar-php

### ISSUE THREAD

**Issue by notgosu** [ladamalina/yii2-rollbar#4]
Hi!

Thank you for your nice work!

Could you upgrade an extension rollbar-php to latest 0.15 version?

**Comment by notgosu** [comment]
up

**Comment by ladamalina** [comment]
@notgosu rollbar version constraint updated. Now it's `~0.11` and allows you to install `rollbar/rollbar (v0.18.2)`

**Comment by notgosu** [comment]
Thanks!
